steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: ['functions', 'deploy', 'myFunction', '--runtime', 'python310', '--entry-point', 'main', 
  '--trigger-event', 'google.storage.object.finalize', '--trigger-resource', 'soa-projects-images']
  dir: ''

# gcloud functions deploy python-http \
# --gen2 \
# --runtime=python310 \
# --region=us-central1 \
# --source=. \
# --entry-point=main \
# --trigger-http \
# --allow-unauthenticated
